name: Security Audit

on:
    push:
        branches: [master, staging, dev]
    pull_request:
        branches: [master, staging, dev]

jobs:
    audit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Install cargo-audit
              run: cargo install cargo-audit

            - name: Run cargo audit
              run: cargo audit
