name: PR Checks

on:
    push:
        branches: [master, staging, dev]
    pull_request:
        branches: [master, staging, dev]

env:
    RUST_TOOLCHAIN: "1.88"

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: ${{ env.RUST_TOOLCHAIN }}
                  components: rustfmt, clippy

            - name: Cache Rust dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Check formatting
              run: cargo fmt --all -- --check

            - name: Run Clippy linter
              run: cargo clippy --all-targets --all-features -- -D warnings

            - name: Run unit tests
              run: cargo test --all --locked --verbose
